controller:
  hostname: controller
  image: mongo:4.0
  command: --smallfiles --replSet cluster-1

replica:
  hostname: replica
  image: mongo:4.0
  command: --smallfiles --replSet cluster-2

test:
  build: .
  volumes:
    - .:/shardmonster
  links:
    - controller
    - replica
